# Generated by Django 5.2.10 on 2026-01-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('activated', 'Activated')], default='pending', max_length=100),
        ),
    ]
